AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a ECR Repository.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Tag Configuration
        Parameters:
          - pLifeCycle
          - pSystemOwner
          - pApplicationName
          - pApplicationNameLC
          - pBusiness
          - pSubDivision
          - pSupportBusiness
          - pSupportCcoeGroup
          - pDataSteward
          - pDataSensitivity
          - pResourceOwner
          - pResourceExposure
          - pResourceSensitivity
          - pPurpose
      - Label:
          default: ECR Configuration
        Parameters:
          - pContainerImageName
          - pImageTagMutability
    ParameterLabels:
      pContainerImageName:
        default: Repository name.
      pImageTagMutability:
        default: Image tag mutability
      pLifeCycle:
        default: Environment LifeCycle
      pSystemOwner:
        default: System Owner
      pApplicationName:
        default: Application Name
      pApplicationNameLC:
        default: Application Name Lower Case
      pBusiness:
        default: Business Division
      pSubDivision:
        default: Sub Division
      pPurpose:
        default: specify the purpose of the resource.
      pSupportBusiness:
        default: Support Business
      pSupportCcoeGroup:
        default: Support CCOE Group
      pDataSteward:
        default: Data Steward
      pDataSensitivity:
        default: Data Sensitivity
      pResourceOwner:
        default: Resource Owner
      pResourceExposure:
        default: Resource Exposure
      pResourceSensitivity:
        default: Resource Sensitivity
Parameters:
  # (((^[a-z0-9]{1,2})|(^[a-z0-9](([a-z0-9-]{0,61})[/]{0,1})+[a-z0-9])([:]([a-zA-Z0-9_.-]{0,126})[a-zA-Z0-9]){0,1})$)
  pContainerImageName:
      Type: String
      AllowedPattern: >-
        ([a-z0-9]{0,}([a-z0-9][/]){0,}([a-z0-9][a-z0-9-]{0,}){0,}){0,}[a-z0-9]$
      Description: |+
        Container Image (ECR) Name (without a preceeding /). Application will be prepended.
        The Image name may contain up to 63 characters. Image names may contain lowercase alphanermuric and dashes.
      Default: 'change-this-value'
        #  and the tag may contain up to 128
        # Further a path can be created using /
        # A tag is an image name followed by a : Further a tag can contain upper and lower case alphanermeric as well as _ . -
        # A repository can contain a single image path but multiple versions using different tag names. An image with no tag is 'latest'

  pImageTagMutability:
    Type: String
    Description: Select if the image tag can be reused (such as latest)
    AllowedValues:
      - IMMUTABLE
      - MUTABLE
    Default: IMMUTABLE

  pLifeCycle:
    Type: String
    Description: Select the environment LifeCycle type
    AllowedValues:
      - Sbx
      - Dev
      - Stg
      - Prd
    ConstraintDescription: The lifecycle must be an allowed value
    Default: Dev

  pSystemOwner:
    Type: String
    Description: |+
      Enter the Active Directory ID of the system owner If you are not sure then use the requestor from the account request spreadsheet.
      It cannot be more than 20 char, and cannot include [ ] : ; | = + * ? < > / \ , @ or non printable characters
    AllowedPattern: >-
      (^[^\x00-\x21\x7f-\xff\[\]:;|=+*?<>/\\,@]{1,20}$)

  pApplicationName:
    Type: String
    Description: Enter the application name. If you are not sure then use the value from the project name in GitLab.
    ConstraintDescription: The application name must be between 1 and 8 characters in length.
    AllowedPattern: >-
      (^[a-zA-Z0-9][a-zA-Z0-9._()-]{0,7}$)
    MinLength: 1
    MaxLength: 8

  pApplicationNameLC:
    Type: String
    Description: Enter the application name with the restriction that is may only be lower case and contain dashes.
    ConstraintDescription: The application name must be between 1 and 8 characters in length and have alphanumeric and dash.
    AllowedPattern: >-
      (^[a-z0-9]([a-z0-9-]{0,6}[a-z0-9]){0,1}$)

  pBusiness:
    Type: String
    Description: Select the Business Division name
    ConstraintDescription: The business division name must be an allowed value
    AllowedValues:
      - ARO
      - BRO
      - CHRO
      - DRO
      - FWRO
      - LARO
      - OCDO
      - MIRO
      - NYRO
      - SFRO
      - SLRO
      - PLRO
      - OC
      - CF
      - DERA
      - ENF
      - IM
      - TM
      - ALJ
      - EBO
      - OA
      - OASB
      - OCA
      - OCIE
      - OCOO
      - OCR
      - OEC
      - OEEO
      - OFM
      - OGC
      - OHR
      - OIA
      - OIAD
      - OIEA
      - OIG
      - OIT
      - OLIA
      - OMS
      - OMWI
      - OPA
      - OS
      - OSO
    Default: OIT

  pSupportBusiness:
    Type: String
    Description: Select the business that is responsible for supporting this solution
    ConstraintDescription: The support business name must be an allowed value
    AllowedValues:
      - ARO
      - BRO
      - CHRO
      - DRO
      - FWRO
      - LARO
      - OCDO
      - MIRO
      - NYRO
      - SFRO
      - SLRO
      - PLRO
      - OC
      - CF
      - DERA
      - ENF
      - IM
      - TM
      - ALJ
      - EBO
      - OA
      - OASB
      - OCA
      - OCIE
      - OCOO
      - OCR
      - OEC
      - OEEO
      - OFM
      - OGC
      - OHR
      - OIA
      - OIAD
      - OIEA
      - OIG
      - OIT
      - OLIA
      - OMS
      - OMWI
      - OPA
      - OS
      - OSO
    Default: OIT

  pSubDivision:
    Description: Define SubDivision which the resources should be tagged with.
    Type: String
    MinLength: 1
    Default: '-'

  pSupportCcoeGroup:
    Type: String
    Description: >-
      Select the CCOE group responsible for supporting this solution if
      applicable
    ConstraintDescription: The support support CCOE group name must be an allowed value
    AllowedValues:
      - DevOps
      - SecOps
      - ArchitectureAndStandards
      - ComplianceAndAssurance
      - Networks
      - BusinessEnablement
      - CostManagement
      - DataGovernance
      - ServiceDelivery
      - ''
    Default: DevOps

  pDataSteward:
    Type: String
    Description: Enter the Active Directory group or user that is the data steward of this solution. If you are not sure then use the requestor from the account request spreadsheet.
    AllowedPattern: >-
      (^[^\x00-\x21\x7f-\xff\[\]:;|=+*?<>/\\,@]{1,20}$)

  pDataSensitivity:
    Type: String
    Description: Select the data sensitivity of data hosted by this solution
    ConstraintDescription: The data sensitivity must be an allowed value
    AllowedValues:
      - Red
      - Amber
      - Green
    Default: Amber

  pResourceOwner:
    Type: String
    Description: Enter the Active Directory group or user that is the resource owner of this solution. If you are not sure then use the requestor from the account request spreadsheet.
    AllowedPattern: >-
      (^[^\x00-\x21\x7f-\xff\[\]:;|=+*?<>/\\,@]{1,20}$)

  pResourceExposure:
    Type: String
    Description: Select the most exposure that this solution is exposed to
    ConstraintDescription: The resource exposure must be an allowed value
    AllowedValues:
      - Public
      - Partner
      - Saas
      - OtherSecCloud
      - AwsGovCloud
      - SecOnPremise
    Default: SecOnPremise

  pResourceSensitivity:
    Type: String
    Description: Select the sensitivity of resources in this solution
    ConstraintDescription: The resource sensitivity must be an allowed value
    AllowedValues:
        - Red
        - Amber
        - Green
    Default: Amber

  pPurpose:
    Type: String
    Description: Select the general purpose of the resource
    ConstraintDescription: The resource purpose must be an allowed value
    AllowedValues:
      - wwws
      - appl
      - daba
      - devo
      - netw
      - secr
      - comp
      - dago
    Default: appl


Mappings:
  NameTagPartitionToPartitionAbbreviation:
    aws-us-gov:
      PartitionAbbr: g
    aws:
      PartitionAbbr: c
  NameTagRegionToRegionAbbreviation:
    us-east-1:
      RegionAbbr: use1
    us-east-2:
      RegionAbbr: use2
    us-west-1:
      RegionAbbr: usw1
    us-west-2:
      RegionAbbr: usw2

  SenstivityMap:
    Sbx:
      ResourceSensitivity: Green
      DataSensitivity: Green
    Dev:
      ResourceSensitivity: Green
      DataSensitivity: Green
    Stg:
      ResourceSensitivity: Amber
      DataSensitivity: Amber
    Prd:
      ResourceSensitivity: Red
      DataSensitivity: Red

  # For DNS
  RegionToRegionAbbreviation:
    us-east-1:
      RegionAbbr: use1
    us-east-2:
      RegionAbbr: use2

  LifeCycleConversionToLowerCase:
    Sbx:
      LowerCase: sbx
    Dev:
      LowerCase: dev
    Stg:
      LowerCase: stg
    Prd:
      LowerCase: prd

  BusinessToLowerCase:
    ALJ:
      LowerCase: alj
    ARO:
      LowerCase: aro
    BRO:
      LowerCase: bro
    CF:
      LowerCase: cf
    CHRO:
      LowerCase: chro
    DERA:
      LowerCase: dera
    DRO:
      LowerCase: dro
    EBO:
      LowerCase: ebo
    ENF:
      LowerCase: enf
    FWRO:
      LowerCase: fwro
    IM:
      LowerCase: im
    LARO:
      LowerCase: laro
    MIRO:
      LowerCase: miro
    NYRO:
      LowerCase: nyro
    OA:
      LowerCase: oa
    OASB:
      LowerCase: oasb
    OC:
      LowerCase: oc
    OCA:
      LowerCase: oca
    OCDO:
      LowerCase: ocdo
    OCIE:
      LowerCase: ocie
    OCOO:
      LowerCase: ocoo
    OCR:
      LowerCase: ocr
    OEC:
      LowerCase: oec
    OEEO:
      LowerCase: oeeo
    OFM:
      LowerCase: ofm
    OGC:
      LowerCase: ogc
    OHR:
      LowerCase: ohr
    OIA:
      LowerCase: oia
    OIAD:
      LowerCase: oiad
    OIEA:
      LowerCase: oiea
    OIG:
      LowerCase: oig
    OIT:
      LowerCase: oit
    OLIA:
      LowerCase: olia
    OMS:
      LowerCase: oms
    OMWI:
      LowerCase: omwi
    OPA:
      LowerCase: opa
    OS:
      LowerCase: os
    OSO:
      LowerCase: oso
    PLRO:
      LowerCase: plro
    SFRO:
      LowerCase: sfro
    SLRO:
      LowerCase: slro
    TM:
      LowerCase: tm

Resources:
  ecrRepository:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: KMS
        # arn:aws:kms:us-east-1:198853884960:alias/ECR
        KmsKey: !Join ['', ['arn:', 'aws:', 'kms:', !Ref "AWS::Region", ':', !Ref "AWS::AccountId", ':', 'alias/', 'ECR'] ]
      ImageScanningConfiguration:
        ScanOnPush: "true"
      ImageTagMutability: !Ref pImageTagMutability
      RepositoryName:
        'Fn::Join': [ "/", [ 'Fn::FindInMap': [ BusinessToLowerCase, Ref: pBusiness, LowerCase ], Ref: pApplicationNameLC, Ref: pContainerImageName ] ]
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: AllowPushPullFromCICDProd
          Effect: Allow
          Principal:
            AWS:
            - arn:aws:iam::033701561153:root
            - arn:aws:iam::690818238031:root
            - arn:aws:iam::567199789269:root
          Action:
          - ecr:BatchCheckLayerAvailability
          - ecr:BatchGetImage
          - ecr:DescribeImages
          - ecr:DescribeRepositories
          - ecr:GetDownloadUrlForLayer
          - ecr:GetLifecyclePolicy
          - ecr:GetLifecyclePolicyPreview
          - ecr:GetRepositoryPolicy
          - ecr:ListImages
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
          - ecr:PutImage
          - ecr:InitiateLayerUpload
          - ecr:UploadLayerPart
          - ecr:CompleteLayerUpload

      Tags:
        - Key: Name
          Value:
            'Fn::Sub':
              - >-
                A-${Partition}${Region}-${pLifeCycle}-${pBusiness}-${pApplicationName}-${Purpose}-${ServiceType}-${cName}
              - Partition: !FindInMap
                  - NameTagPartitionToPartitionAbbreviation
                  - !Ref 'AWS::Partition'
                  - PartitionAbbr
                Region: !FindInMap
                  - NameTagRegionToRegionAbbreviation
                  - !Ref 'AWS::Region'
                  - RegionAbbr
                Purpose: !Ref pPurpose
                ServiceType: Repository
                cName: !Ref pContainerImageName
        - Key: LifeCycle
          Value: !Ref pLifeCycle
        - Key: SystemOwner
          Value: !Ref pSystemOwner
        - Key: ApplicationName
          Value: !Ref pApplicationName
        - Key: Business
          Value: !Ref pBusiness
        - Key: SupportBusiness
          Value: !Ref pSupportBusiness
        - Key: SupportCcoeGroup
          Value: !Ref pSupportCcoeGroup
        - Key: DataSteward
          Value: !Ref pDataSteward
        - Key: DataSensitivity
          Value: !Ref pDataSensitivity
        - Key: ResourceOwner
          Value: !Ref pResourceOwner
        - Key: ResourceSensitivity
          Value: !Ref pResourceSensitivity
        - Key: ResourceExposure
          Value: !Ref pResourceExposure
        - Key: SubDivision
          Value: !Ref pSubDivision

