\set ON_ERROR_STOP
BEGIN;
ALTER TABLE "ops1"."property" ALTER COLUMN "dtcreated" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ops1"."property" ALTER COLUMN "dtend" SET DEFAULT CAST('12/31/9999 23:59:59.997',(0 AS datetime));
ALTER TABLE "ops1"."property" ALTER COLUMN "dtstart" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ops1"."userrole" ALTER COLUMN "dtend" SET DEFAULT CAST('12/31/9999 23:59:59.997',(0 AS datetime));
ALTER TABLE "ops1"."userrole" ALTER COLUMN "dtstart" SET DEFAULT CURRENT_TIMESTAMP;
COMMIT;
