\set ON_ERROR_STOP
BEGIN;
ALTER TABLE "norm2_ops"."maxdfeedback" ALTER COLUMN "dtcreated" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "norm2_ops"."maxdspreferences46" ALTER COLUMN "dt" SET DEFAULT CURRENT_TIMESTAMP;
COMMIT;
